name: avaruussaa_flutter
description: Avaruussään Flutter versio.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  http: ^1.0.0
  local_notifier: ^0.1.5
  shared_preferences: ^2.1.1
  system_tray: ^2.0.3
  url_launcher: ^6.1.11
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1
  freezed: ^2.4.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
